server:
  port: 9090
  context-path: #/liuzh/

logging:
  level:
    tk.mybatis: TRACE

#druid:
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://ilovemldu.mysql.rds.aliyuncs.com:3506/petrocoke_dev?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
#  username: petrocoke_dev
#  password: petrocoke_dev123
#  initial-size: 1
#  min-idle: 1
#  max-active: 20
#  test-on-borrow: true

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
  datasource:
    name: datasource
    initialize: false
    url: jdbc:mysql://ilovemldu.mysql.rds.aliyuncs.com:3506/petrocoke_dev?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
    username: petrocoke_dev
    password: petrocoke_dev123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      max-active: 2
      min-idle: 2
      initial-size: 2
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 3000
      max-wait: 3000
    jmx-enabled: true

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql